### ISSUE TITLE
[Bug] Object.entries not found on iOS 10.2

### ISSUE THREAD

**Issue by anhnhoktvn** [xkjyeah/vue-google-maps#412]
Upgrading from version 0.8.4 to 0.9.7 make my website stop working on iOS 10.2.
Edit: The example page also can not run on iOS 10.2. 
[http://xkjyeah.github.io/vue-google-maps/overlay.html](http://xkjyeah.github.io/vue-google-maps/overlay.html)

**Comment by anhnhoktvn** [comment]
Here is the error on iOS 10.2.
```
TypeError: Object.entries is not a function. (In 'Object.entries(mappedProps)', 'Object.entries' is undefined)
```
 Maybe we need to add some polyfills to babel

**Comment by xkjyeah** [comment]
You have to add 'babel-polyfill' to the 'entry' property in webpack config.

**Comment by tsarrB** [comment]
![image](https://user-images.githubusercontent.com/17804685/55036394-2b2da580-5023-11e9-9f26-4fa67eea830c.png)
it works for me
